version: 2.1

orbs:
  python: circleci/python@2

jobs:
  test-python:
    docker:
      - image: cimg/python:3.8-node
    working_directory: ~/project/scripts
    steps:
      - checkout:
          path: ~/project
      - python/install-packages
      - run:
          name: Run tests
          command: pytest --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '# e.g. ./deploy.sh'
      - run:
          name: found github actions config
          command: ':'

workflows:
  build-and-test:
    jobs:
<<<<<<< HEAD
      - test-python
      # Uncomment when ready for deployment
      # - deploy:
      #     requires:
      #       - test-python
=======
      - build:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - build:
          type approval
          filters
            branches
              ignore /.*/
            tags
              ignore /.*/
          requires []
          context 
            - build
          matrix
            alias "pr-build"
          name build_pull_request
          filters
            branches
              ignore master
  release:
    jobs:
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
    when:
      and:
        - equal: [ tag, << pipeline.trigger_source >> ]
        - matches: 
            pattern: "^v"
            value: << pipeline.git.tag >>
>>>>>>> 474eaf8edbf4f68c289e4ff2c2b1e1d786d8d070
